---
title: Tables Results
author:
  - name: Stefan Kunz
date: last-modified
format: 
  
  html:
    self-contained: true
    number-sections: false
    number-depth: 3
    anchor-sections: true
    code-tools: true
    code-fold: false
    code-link: false
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    mainfont: Source Sans Pro
    theme: journal
    toc: true
    toc-depth: 3
    toc-location: left
    captions: true
    cap-location: margin
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
comments:
  hypothesis: true
execute:
  warning: false
  message: false
  echo : false
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
source("/home/kunzst/Dokumente/Projects/Trait_DB/Trait-group-environment-relationships/R/Set_up.R")
```

```{r}
mtps_genera <- readRDS(file.path(path_cache, "mtps_genera.rds"))
mtps_family <- readRDS(file.path(path_cache, "mtps_family.rds"))

create_deftraits_table <- function(x,
                                   table_name) {
    x[mean_affinity >= 0.5,
        defining_tc := paste(trait, collapse = ", "),
        by = "group"
    ]

    defining_traits <- x[!is.na(defining_tc), ] %>%
        .[order(group), .(group, n_taxa_group, defining_tc)] %>%
        unique(.)
    defining_traits[x[trait == "sensitivity_organic", ],
        mean_sensitivity_organic := i.mean_affinity,
        on = "group"
    ]
    defining_traits[, mean_sensitivity_organic := round(mean_sensitivity_organic, digits = 4)]

    # save
    saveRDS(defining_traits, file.path(path_cache, paste0(table_name,".rds")))
    fwrite(defining_traits, file.path(path_paper, "Tables", paste0(table_name, ".csv")), sep = ";")

    # interactive table
    reactable(
        defining_traits[order(group), ],
        columns = list(
            group = colDef(name = "TPG", width = 60),
            n_taxa_group = colDef(name = "Nr. taxa per TPG", width = 100),
            defining_tc = colDef(
                name = "Defining trait combinations"
            ),
            mean_sensitivity_organic = colDef(name = "Mean S_org", width = 100)
        ),
        filterable = TRUE,
        highlight = TRUE,
        defaultPageSize = 20
    )
}

# For North American trait DB taxa 
create_deftraits_table(x = mtps_family, table_name = "defining_traits_family")
create_deftraits_table(x = mtps_genera, table_name = "defining_traits_genus")
```
